baseurl = "https://www.cs.toronto.edu/csgsbs"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 7
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "CSGSBS @ UofT"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "CSGSBS @ UofT"
      logoHomeLink = "/csgsbs"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "$HOME"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "constitution"
        name = "Constitution"
        url = "/constitution.pdf"
      [[languages.en.menu.main]]
        identifier = "cookies"
        name = "Cookie Breaks"
        url = "/posts/cookie-breaks"
      [[languages.en.menu.main]]
        identifier = "dcs"
        name = "Resources"
        url = "https://web.cs.toronto.edu/graduate/current-students"